### ISSUE TITLE
add opportunity to create multiple files from single source (`files` section)

### ISSUE THREAD

**Issue by kozmod** [kozmod/progen#36]
current realization:
```
files:
  - path: x/config.yaml
    get:
      url: "{{printf `%s%s%s` $gitlab_path `config_tmpl.yaml` $gitlab_raw_suffix}}"
```
possible usage:
```
files:
  - path: [x/config_dev.yaml, x/config_stage.yaml, x/config_prod.yaml]
    get:
      url: "{{printf `%s%s%s` $gitlab_path `config_tmpl.yaml` $gitlab_raw_suffix}}"
```
