### ISSUE TITLE
pipe command execution (`cmd`)  

### ISSUE THREAD

**Issue by kozmod** [kozmod/progen#37]
```yaml
## befor v0.0.9
cmd1:
  - cd  /  && pwd

## from v0.0.9
 cmd:
  - exec: [cd  /  && pwdl]
    dir: /some_dir
```
in current realization, execution command in pipe works incorrect
