### ISSUE TITLE
add file/dir permission option to config

### ISSUE THREAD

**Issue by kozmod** [kozmod/progen#4]
current realization create files and dirs with `0777` (all can read/write/search) as default permission
```
-rwxr-xr-x     1  user  grp  416 Jan 16 08:05 Makefile
drwxrwxrwx  2 user  grp   64 Jan 16 08:05 api
```
need to add an opportunity to set permissions of generated files and dirs

config example:
```yaml
dir:
  - internal/client # 1️⃣
  - path: pkg/somedir # 2️⃣
    perm: 0660

files:
  - path: project/Dockerfile # 3️⃣
    perm: 0755
    template: false
    get:
      url: "{{ .vars.REPO_2_FILE_PATH }}Dockerfile{{ .vars.REPO_2_SUFFIX }}"
```
1️⃣  declaration of recursive dirs creation (`mkdir -p`) with `0777` permissions
2️⃣  declaration of recursive dirs creation  with setting `0660` permissions to the last dir (`somedir `)
3️⃣ declaration of recursive dirs creation  with setting `0755 ` permissions to the file  (`Dockerfile `)
