### ISSUE TITLE
add `random` functions which could be execute on template

### ISSUE THREAD

**Issue by kozmod** [kozmod/progen#40]
Need to add functions which could be execute during `text/template` __execution__

First step - add `random` string generation functions

For Example: 
https://docs.gomplate.ca/functions/random/
https://github.com/hairyhenderson/gomplate
```
{{- $db_pass := random.AlphaNum 16 }}
{{- $db_user := "ci" }}
services:
  postgres:
    container_name: postgres-for-some-service
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=some
      - POSTGRES_PASSWORD={{ $db_pass }}
      - POSTGRES_USER={{ $db_user }}
```
👇🏻
```
services:
  postgres:
    container_name: postgres-for-some-service
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=some
      - POSTGRES_PASSWORD= 4olRl9mRmVp1nqSm
      - POSTGRES_USER=ci
```
