### ISSUE TITLE
short declaration for `cmd` actions

### ISSUE THREAD

**Issue by kozmod** [kozmod/progen#57]
Now declaration of `cmd` is too complicated for "simple" cases
```
cmd:
  - exec:
      - pwd
    dir: .
```
it will be nice declared simple cases as 
```
cmd:
  - pwd
```
